<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin_user by admin_id
     */
    function get_admin_user($admin_id)
    {
        return $this->db->get_where('admin_users',array('admin_id'=>$admin_id))->row_array();
    }
        
    /*
     * Get all admin_users
     */
    function get_all_admin_users()
    {
        
		return $this->db->query("select a.*,z.zilla_name from admin_users a left join zilla z on a.zilla_id=z.zilla_id  order by a.admin_id DESC")->result_array();

    }
        
    /*
     * function to add new admin_user
     */
    function add_admin_user($params)
    {
        $this->db->insert('admin_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin_user
     */
    function update_admin_user($admin_id,$params)
    {
        $this->db->where('admin_id',$admin_id);
        return $this->db->update('admin_users',$params);
    }
    
    /*
     * function to delete admin_user
     */
    function delete_admin_user($admin_id)
    {
        return $this->db->delete('admin_users',array('admin_id'=>$admin_id));
    }
}
