<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Volunteer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get volunteer by volunteer_id
     */
    function get_volunteer($volunteer_id)
    {
        return $this->db->get_where('volunteers',array('volunteer_id'=>$volunteer_id))->row_array();
    }

    /*
     * Get volunteer by volunteer_mobileno
     */
    function get_volunteer_by_mobileno($mobile_no)
    {
		
        return $this->db->get_where('volunteers',array('mobile_no'=>$mobile_no))->row_array();
    }
	
    /*
     * Get all volunteers
     */
    function get_all_volunteers()
    {
		$zilla_id = $this->session->userdata('zilla_id');
		if($zilla_id != 0){
			$where = "where v.zilla_id=".$zilla_id;
		}else{
			$where = "";
		}
		
		return $this->db->query("select v.*,z.zilla_name from volunteers v left join zilla z on v.zilla_id=z.zilla_id ".$where." order by v.volunteer_id DESC")->result_array();
        /*$this->db->order_by('volunteer_id', 'desc');
        return $this->db->get('volunteers')->result_array();*/
    }
        
    /*
     * function to add new volunteer
     */
    function add_volunteer($params)
    {
        $this->db->insert('volunteers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update volunteer
     */
    function update_volunteer($volunteer_id,$params)
    {
        $this->db->where('volunteer_id',$volunteer_id);
        return $this->db->update('volunteers',$params);
    }
    
    /*
     * function to delete volunteer
     */
    function delete_volunteer($volunteer_id)
    {
        return $this->db->delete('volunteers',array('volunteer_id'=>$volunteer_id));
    }
}
