<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vw_contact_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vw_contact by 
     */
    function get_vw_contact($id)
    {
        return $this->db->get_where('vw_contacts',array('contact_id'=>$id))->row_array();
    }
        
    /*
     * Get all vw_contacts
     */
    function get_all_vw_contacts()
    {
		$zilla_id = $this->session->userdata('zilla_id');
		if($zilla_id != 0){
			$this->db->where(array('zilla_id'=>$zilla_id));
		}
        $this->db->order_by('', 'desc');
        return $this->db->get('vw_contacts')->result_array();
    }
        
    /*
     * function to add new vw_contact
     */
    function add_vw_contact($params)
    {
        $this->db->insert('contacts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vw_contact
     */
    function update_vw_contact($id,$params)
    {
        $this->db->where('contact_id',$id);
        return $this->db->update('contacts',$params);
    }
    
    /*
     * function to delete vw_contact
     */
    function delete_vw_contact($id)
    {
        return $this->db->delete('vw_contacts',array('id'=>$id));
    }
}
